version: '3'

services:

  spydb:
    image: postgres:13
    container_name: spydb
    restart: unless-stopped
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      spy:
        aliases:
          - postgres.spy
    volumes:
      - $PGDATA_DIR:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB

networks:
  spy:


