version: '3'

services:

  spydb:
    image: postgres:13
    container_name: spydb
    restart: unless-stopped
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      spy:
        aliases:
          - postgres.spy
    volumes:
      - $PGDATA_DIR:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB

  looker:
    image: node:erbium-alpine3.10
    container_name: looker
    restart: unless-stopped
    volumes:
      - $PWD:/usr/src/app
      - $JSONDB_DIR:/usr/src/db
    environment:
      - JSONDB_DIR=/usr/src/db
      - LIMIT=$LIMIT
      - LOOPTIME=$LOOPTIME
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
      - NODE_ENV=$NODE_ENV
      - COINMARKETCAP_KEY=$COINMARKETCAP_KEY
      - LOOKER_PASSWORD=$LOOKER_PASSWORD
    networks:
      spy:
        aliases:
          - looker.spy
    working_dir: /usr/src/app
    command: npm run looker

  cryptoexplorer:
    image: crypto-explorer:latest
    container_name: explorer
    restart: unless-stopped
    expose:
      - 8501
    ports:
      - 8501:8501
    networks:
      spy:
        aliases:
          - explorer.spy
    environment:
      - PG_CONF=$PG_CONF
      - VIRTUAL_HOST=$VIRTUAL_HOST



networks:
  spy:


